Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  # Выделяем ресурсы для стабильной работы локальных кластеров k8s
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  # Автоматическая установка Docker Engine и плагина Compose
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y ca-certificates curl gnupg lsb-release
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://docker.com | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://docker.com $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    
    # Добавляем пользователя vagrant в группу docker
    usermod -aG docker vagrant
  SHELL
end
