# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Настройка ВМ Server
  config.vm.define "server" do |server|
    server.vm.hostname = "server.local"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.provision "shell", path: "provision_server.sh"
  end

  # Настройка ВМ Client
  config.vm.define "client" do |client|
    client.vm.hostname = "client.local"
    client.vm.network "private_network", ip: "192.168.56.20"
    client.vm.provision "shell", path: "provision_client.sh"
  end
end
