Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Пробрасываем порты: 8082 на хосте -> 80 в ВМ (чтобы не пересекаться с lesson16)
  config.vm.network "forwarded_port", guest: 80, host: 8082, auto_correct: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    # Даем уникальное имя машине для 17-го урока
    vb.name = "codeby-wordpress-environment"
  end

  # Автоматическая установка Docker при запуске
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y docker.io
    sudo usermod -aG docker vagrant
  SHELL
end
