apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secrets
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.rootPassword | quote }}
  mysql-password: {{ .Values.mysql.password | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-config
data:
  mysql-database: {{ .Values.mysql.database | quote }}
  mysql-user: {{ .Values.mysql.user | quote }}
